apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hello
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
    spec:
      containers:
      - name: hello
        image: webapp:latest
        ports:
        - containerPort: 80
