apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:latest
        ports:
        - containerPort: 80
